name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NextJs App
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }} # Your server's IP address
          username: ${{ secrets.SSH_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_KEY }} # Your server's SSH private key

          script: |
            cd /home/react/wv-react
            echo $USER . " logged in successfully"